# Generated by Django 3.0.8 on 2020-07-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200727_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
