# Generated by Django 3.0.8 on 2020-07-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200728_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='image',
        ),
    ]
